In [1]:
import pandas as pd 
import numpy as np
from IPython.display import display
import sys, os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import mannwhitneyu
import missingno as msno
%matplotlib inline
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
#from functions.transformers import *
from functions.eda_functions import test_mcar, list_missing_values

In [2]:
useTrain = pd.read_csv('../data/raw/train.csv').drop('Id', axis=1).reset_index(drop=True)
df_raw_info = pd.DataFrame({
    'columns': useTrain.columns,
    'nulls': useTrain.isnull().sum(),
    'dtypes': useTrain.dtypes,
}).reindex(columns=['columns', 'nulls', 'dtypes']).sort_values(by='nulls', ascending=False)
display(df_raw_info[(df_raw_info['dtypes'] != 'str')].reset_index(drop=True))
display(df_raw_info[(df_raw_info['dtypes'] == 'str')].reset_index(drop=True))

          columns  nulls   dtypes
0     LotFrontage    259  float64
1     GarageYrBlt     81  float64
2      MasVnrArea      8  float64
3         LotArea      0    int64
4      MSSubClass      0    int64
5       BsmtUnfSF      0    int64
6     TotalBsmtSF      0    int64
7      BsmtFinSF1      0    int64
8    YearRemodAdd      0    int64
9     OverallQual      0    int64
10      YearBuilt      0    int64
11    OverallCond      0    int64
12   BsmtHalfBath      0    int64
13   BsmtFullBath      0    int64
14      GrLivArea      0    int64
15   LowQualFinSF      0    int64
16       2ndFlrSF      0    int64
17       1stFlrSF      0    int64
18     BsmtFinSF2      0    int64
19     Fireplaces      0    int64
20   TotRmsAbvGrd      0    int64
21   KitchenAbvGr      0    int64
22       FullBath      0    int64
23       HalfBath      0    int64
24     GarageCars      0    int64
25     GarageArea      0    int64
26   BedroomAbvGr      0    int64
27  EnclosedPorch      0    int64
28      3SsnPorch      0    int64
29    OpenPorchSF      0    int64
30     WoodDeckSF      0    int64
31       PoolArea      0    int64
32    ScreenPorch      0    int64
33        MiscVal      0    int64
34         MoSold      0    int64
35         YrSold      0    int64
36      SalePrice      0    int64

          columns  nulls dtypes
0          PoolQC   1453    str
1     MiscFeature   1406    str
2           Alley   1369    str
3           Fence   1179    str
4      MasVnrType    872    str
5     FireplaceQu    690    str
6      GarageQual     81    str
7      GarageType     81    str
8    GarageFinish     81    str
9      GarageCond     81    str
10   BsmtExposure     38    str
11   BsmtFinType2     38    str
12       BsmtQual     37    str
13   BsmtFinType1     37    str
14       BsmtCond     37    str
15     Electrical      1    str
16       BldgType      0    str
17   Neighborhood      0    str
18      LandSlope      0    str
19     Condition2      0    str
20     Condition1      0    str
21    LandContour      0    str
22       LotShape      0    str
23         Street      0    str
24       MSZoning      0    str
25      LotConfig      0    str
26      Utilities      0    str
27     HouseStyle      0    str
28     Foundation      0    str
29      ExterQual      0    str
30      ExterCond      0    str
31        Heating      0    str
32    Exterior2nd      0    str
33    Exterior1st      0    str
34       RoofMatl      0    str
35      RoofStyle      0    str
36     CentralAir      0    str
37      HeatingQC      0    str
38    KitchenQual      0    str
39     Functional      0    str
40     PavedDrive      0    str
41       SaleType      0    str
42  SaleCondition      0    str

Numero de features --> 73
categoricas 37 --> ['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
                    'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
					'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
					'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
					'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']
					
numericas 36 --> ['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea',
			      'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea',
				  'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
				  'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch',
				  '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']