In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display as dsp
%matplotlib inline
os.chdir('..')

df = pd.read_csv("./data/raw/train.csv")
use_df = df.copy()

In [2]:
from functions.utilsMethods import UtilsMethods
print(df.shape)

utils = UtilsMethods(use_df)
features_missing_values = utils.createFeaturesMissingValuesList()

(1460, 81)

              missingCounts  percentage(%)  presentCounts     type
PoolQC                 1453          99.52              7      str
MiscFeature            1406          96.30             54      str
Alley                  1369          93.77             91      str
Fence                  1179          80.75            281      str
MasVnrType              872          59.73            588      str
FireplaceQu             690          47.26            770      str
LotFrontage             259          17.74           1201  float64
GarageType               81           5.55           1379      str
GarageYrBlt              81           5.55           1379  float64
GarageFinish             81           5.55           1379      str
GarageQual               81           5.55           1379      str
GarageCond               81           5.55           1379      str
BsmtExposure             38           2.60           1422      str
BsmtFinType2             38           2.60           1422      str
BsmtQual                 37           2.53           1423      str
BsmtCond                 37           2.53           1423      str
BsmtFinType1             37           2.53           1423      str
MasVnrArea                8           0.55           1452  float64
Electrical                1           0.07           1459      str

In [3]:
from functions.numeric_missing_correlations import NumericMissingCorrelations
from functions.effect_size_and_direction import EffectSizeAndDirection
from functions.test_normal_distribution import NormalDistributionTest
nmc = NumericMissingCorrelations(dataFrame=use_df)
tnd = NormalDistributionTest(dataFrame=use_df)

In [4]:
# PoolQC: Calidad de la piscina.
# Ex	Excellent (Excelente)
# Gd	Good (Bueno)
# TA	Average/Typical (Promedio/Típico)
# Fa	Fair (Justo/Regular)
# NA	No Pool (Sin piscina)

uniques = use_df["PoolQC"].unique()
print(f"Categorias presentes -> {uniques.tolist()}")

resPoolQC = nmc.mannWhitneyU(featureMissingValues="PoolQC",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)  
resPoolQC = resPoolQC.apply(lambda x: x.round(5)).sort_values(by="p_value")
resPoolQC[(resPoolQC["evidence_MAR"]) & (resPoolQC["p_value"] < 0.05) & (resPoolQC["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
# ---------------------
# PoolQC vs PoolArea:
# p_value < 0.05 (valor -> 0.0)
# effect_size > 0.1 (valor -> 1.0)
# direction (valor -> -555.0)
# ---------------------
# El valor de p_value y effect_size son perfectos, se concluye que es un faltante estructural
# Estrategia:
#     - Se reemplaza missing values por categoria "NA"
# ---------------------
# La variable de relacion de nulos es numerica continua (LotArea)

Categorias presentes -> [nan, 'Ex', 'Fa', 'Gd']

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
0,PoolArea,0.0,0.00000,True,1.00000,-555.0,negative,Grande
1,LotArea,1493.0,0.00125,True,0.70642,-7239.0,negative,Grande
2,Fireplaces,1883.0,0.00135,True,0.62973,0.0,negative,Grande
3,LotFrontage,1104.0,0.00338,True,0.69205,-51.0,negative,Grande
4,BedroomAbvGr,2332.5,0.00615,True,0.54134,-1.0,negative,Grande
5,1stFlrSF,2085.0,0.00702,True,0.59001,-306.0,negative,Grande
6,BsmtFullBath,2566.0,0.00820,True,0.49543,-1.0,negative,Mediano
7,GrLivArea,2178.0,0.00899,True,0.57172,-1325.0,negative,Grande
8,BsmtFinSF2,3485.5,0.00930,True,0.31462,0.0,negative,Mediano
9,LowQualFinSF,4444.0,0.01192,True,0.12614,0.0,negative,Pequeño
10,2ndFlrSF,2722.0,0.01880,True,0.46475,-950.0,negative,Mediano
11,TotRmsAbvGrd,2609.5,0.02307,True,0.48687,-2.0,negative,Mediano
12,SalePrice,2602.0,0.02566,True,0.48835,-72100.0,negative,Mediano
13,YrSold,7499.0,0.02653,True,0.47458,2.0,positive,Mediano
14,BsmtFinSF1,2672.0,0.02747,True,0.47458,-409.0,negative,Mediano
15,OverallQual,2732.0,0.03010,True,0.46279,-1.0,negative,Mediano

In [5]:
use_df["PoolQC"] = use_df["PoolQC"].fillna("NA")

In [6]:
# MiscFeature: Característica miscelánea no cubierta en otras categorías.
# 
# Elev	Elevator (Ascensor)
# Gar2	2nd Garage (if not described in garage section) (Segundo garaje (si no se describe en la sección de garaje))
# Othr	Other (Otro)
# Shed	Shed (over 100 SF) (Caseta (más de 100 pies cuadrados))
# TenC	Tennis Court (Cancha de tenis)
# NA	None (Ninguna)
uniquesMiscFeature = use_df["MiscFeature"].unique()
print(f"Unique values in MiscFeature: {uniquesMiscFeature}")

resMiscFeature = nmc.mannWhitneyU(featureMissingValues="MiscFeature",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)
resMiscFeature = resMiscFeature.apply(lambda x: x.round(5)).sort_values(by="p_value")
resMiscFeature[(resMiscFeature["evidence_MAR"]) & (resMiscFeature["p_value"] < 0.05) & (resMiscFeature["rankBiseral"].abs() > 0.1)].reset_index(drop=True)

# ---------------------
# MiscFeature vs MiscVal
# p_value < 0.05 (valor -> 0.0)
# effect_size > 0.1 (valor 0.963)
# direction -500.0
# ---------------------
# El valor de p_value y effect_size son perfectos, se concluye que es un faltante estructural
# Estrategia:
#     - Se reemplaza missing values por categoria "NA"
# ---------------------
# La variable de relacion de nulos es numerica continua (MiscVal)

Unique values in MiscFeature: <StringArray>
[nan, 'Shed', 'Gar2', 'Othr', 'TenC']
Length: 5, dtype: str

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
0,MiscVal,1406.0,0.00000,True,0.96296,-500.0,negative,Grande
1,YearRemodAdd,49328.5,0.00018,True,0.29942,19.0,positive,Pequeño
2,OverallQual,48840.5,0.00024,True,0.28656,1.0,positive,Pequeño
3,YearBuilt,48871.0,0.00033,True,0.28737,13.5,positive,Pequeño
4,OverallCond,28822.0,0.00086,True,0.24077,-1.0,negative,Pequeño
5,GarageYrBlt,41356.5,0.00725,True,0.22125,10.0,positive,Pequeño
6,SalePrice,46022.5,0.00802,True,0.21233,18250.0,positive,Pequeño
7,TotalBsmtSF,45540.0,0.01269,True,0.19962,115.0,positive,Pequeño
8,GarageCars,44726.0,0.01299,True,0.17818,0.0,positive,Pequeño
9,LotArea,30843.5,0.01922,True,0.18752,-996.0,negative,Pequeño
10,FullBath,43677.0,0.03177,True,0.15055,1.0,positive,Pequeño
11,GrLivArea,44446.0,0.03297,True,0.17080,207.0,positive,Pequeño
12,MasVnrArea,43425.0,0.03476,True,0.15045,0.0,positive,Pequeño
13,YrSold,31738.0,0.03625,True,0.16395,0.0,negative,Pequeño

In [7]:
use_df['MiscFeature'] = use_df['MiscFeature'].fillna('NA')

In [8]:
# Alley: Tipo de acceso por callejón a la propiedad.
# Grvl	Gravel (Grava)
# Pave	Paved (Pavimentado)
# NA 	No alley access (Sin acceso por callejón)

uniquesAlley = use_df["Alley"].unique()
print(f"Unique values in Alley: {uniquesAlley}")

resAlley = nmc.mannWhitneyU(featureMissingValues="Alley",  effectSizeAndDirection=EffectSizeAndDirection.rank_biserial)
resAlley = resAlley.apply(lambda x: x.round(7)).sort_values(by="rankBiseral", ascending=False)
resAlley[(resAlley["evidence_MAR"]) & (resAlley["p_value"] < 0.05) & (resAlley["rankBiseral"].abs() > 0.1)].reset_index(drop=True)
# ---------------------
# Alley vs MSSubClass
# p_value < 0.05 (valor -> 0.0)
# effect_size > 0.1 (valor 0.31)
# direction -20.0

Unique values in Alley: <StringArray>
[nan, 'Grvl', 'Pave']
Length: 3, dtype: str

,feature,stat,p_value,evidence_MAR,rankBiseral,diff_means,direction,interpretation
0,LotFrontage,71623.0,0.000000e+00,True,0.493858,10.0,positive,Mediano
1,YearBuilt,90375.0,0.000000e+00,True,0.450887,50.0,positive,Mediano
2,TotalBsmtSF,87698.5,0.000000e+00,True,0.407918,244.0,positive,Mediano
3,BsmtFinSF1,85755.0,0.000000e+00,True,0.376717,405.0,positive,Mediano
4,1stFlrSF,84721.0,0.000000e+00,True,0.360117,162.0,positive,Mediano
5,LotArea,82102.5,4.000000e-07,True,0.318079,1450.0,positive,Mediano
6,MSSubClass,42711.0,2.000000e-07,True,0.314315,-20.0,negative,Mediano
7,SalePrice,81078.0,1.400000e-06,True,0.301632,25000.0,positive,Mediano
8,EnclosedPorch,43510.5,0.000000e+00,True,0.301479,0.0,negative,Mediano
9,WoodDeckSF,80222.5,7.000000e-07,True,0.287898,0.0,positive,Pequeño
10,GarageYrBlt,68157.5,1.830000e-05,True,0.281710,26.5,positive,Pequeño
11,MasVnrArea,77322.0,2.900000e-06,True,0.261576,0.0,positive,Pequeño
12,Fireplaces,78469.5,3.700000e-06,True,0.259755,1.0,positive,Pequeño
13,2ndFlrSF,46819.0,1.110000e-05,True,0.248364,-612.0,negative,Pequeño
14,BsmtFullBath,76053.5,3.670000e-05,True,0.220968,0.0,positive,Pequeño
15,GarageArea,74137.5,2.345700e-03,True,0.190209,40.0,positive,Pequeño
16,BsmtUnfSF,51484.5,5.520200e-03,True,0.173464,-189.0,negative,Pequeño
17,OverallCond,52541.0,5.535300e-03,True,0.156503,-1.0,negative,Pequeño
18,GarageCars,71767.5,6.580400e-03,True,0.152161,0.0,positive,Pequeño
19,OverallQual,71092.0,2.044580e-02,True,0.141316,0.0,positive,Pequeño

In [9]:
listFeatures = ["Alley", "LotFrontage"]
testAlley = use_df.copy()
testAlley['Alley'] = testAlley['Alley'].fillna('NA')
testAlley[testAlley['Alley'] == 'NA'].groupby(listFeatures)["Alley"].count()

Alley  LotFrontage
NA     21.0           23
       24.0           14
       30.0            1
       32.0            5
       33.0            1
                      ..
       160.0           1
       168.0           1
       174.0           2
       182.0           1
       313.0           2
Name: Alley, Length: 108, dtype: int64

In [10]:
utils.createFeaturesMissingValuesList()

              missingCounts  percentage(%)  presentCounts     type
Alley                  1369          93.77             91      str
Fence                  1179          80.75            281      str
MasVnrType              872          59.73            588      str
FireplaceQu             690          47.26            770      str
LotFrontage             259          17.74           1201  float64
GarageType               81           5.55           1379      str
GarageYrBlt              81           5.55           1379  float64
GarageFinish             81           5.55           1379      str
GarageQual               81           5.55           1379      str
GarageCond               81           5.55           1379      str
BsmtFinType2             38           2.60           1422      str
BsmtExposure             38           2.60           1422      str
BsmtCond                 37           2.53           1423      str
BsmtQual                 37           2.53           1423      str
BsmtFinType1             37           2.53           1423      str
MasVnrArea                8           0.55           1452  float64
Electrical                1           0.07           1459      str

Index(['Alley', 'Fence', 'MasVnrType', 'FireplaceQu', 'LotFrontage',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond',
       'BsmtFinType2', 'BsmtExposure', 'BsmtCond', 'BsmtQual', 'BsmtFinType1',
       'MasVnrArea', 'Electrical'],
      dtype='str')